# basic options this will not be shown anywhere because this YML and is calles a hash or hashtag. 
# It's going to be ignored by the computer because its human language
title: Dorky is a title
author: Dorky 101
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  starsassault

# Build settings. 
markdown: kramdown
theme: minima

# That before the double column is called a action and after it is the value. Don't forget the spaces in the markdown!
